<%@ page defaultCodec="none" %>
<%@ page contentType="text/html;charset=UTF-8" %>
This message was automatically generated by <g:message code="default.application.name"/>. Please do not reply to this message directly.

This message is to notify that <g:message code="project.name.label"/> "${projectName}" has been completed; all created tasks have been transcribed.

