/*
 *  Copyright (C) 2011 Atlas of Living Australia
 *  All Rights Reserved.
 * 
 *  The contents of this file are subject to the Mozilla Public
 *  License Version 1.1 (the "License"); you may not use this file
 *  except in compliance with the License. You may obtain a copy of
 *  the License at http://www.mozilla.org/MPL/
 * 
 *  Software distributed under the License is distributed on an "AS
 *  IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 *  implied. See the License for the specific language governing
 *  rights and limitations under the License.
 */

package au.org.ala.volunteer

/**
 * Enum class for Darwin Core Field names
 * DwC fields taken from http://rs.tdwg.org/dwc/terms/index.htm
 * 
 * @author "Nick dos Remedios <Nick.dosRemedios@csiro.au>"
 */
enum DarwinCoreField {
    institutionID("Institution ID"),
    collectionID("Collection ID"),
    datasetID("Dataset ID"),
    institutionCode("Institution Code"),
    collectionCode("Collection Code"),
    datasetName("Dataset Name"),
    ownerInstitutionCode("Owner Institution Code"),
    basisOfRecord("Basis Of Record"),
    informationWithheld("Information Withheld"),
    dataGeneralizations("Data Generalizations"),
    dynamicProperties("Dynamic Properties"),
    occurrenceID("Occurrence ID"),
    catalogNumber("Catalog Number"),
    occurrenceDetails("Occurrence Details"),
    occurrenceRemarks("Occurrence Remarks"),
    recordNumber("Record Number"),
    recordedBy("Recorded By"),
    recordedByID("Recorded By ID"),
    individualID("Individual ID"),
    individualCount("Individual Count"),
    sex("Sex"),
    lifeStage("Life Stage"),
    reproductiveCondition("Reproductive Condition"),
    behavior("Behavior"),
    establishmentMeans("Establishment Means"),
    occurrenceStatus("Occurrence Status"),
    preparations("Preparations"),
    disposition("Disposition"),
    otherCatalogNumbers("Other Catalog Numbers"),
    previousIdentifications("Previous Identifications"),
    associatedMedia("Associated Media"),
    associatedReferences("Associated References"),
    associatedOccurrences("Associated Occurrences"),
    associatedSequences("Associated Sequences"),
    associatedTaxa("Associated Taxa"),
    eventID("Event ID"),
    samplingProtocol("Sampling Protocol"),
    samplingEffort("Sampling Effort"),
    eventDate("Event Date"),
    eventTime("Event Time"),
    startDayOfYear("Start Day Of Year"),
    endDayOfYear("End Day Of Year"),
    year("Year"),
    month("Month"),
    day("Day"),
    verbatimEventDate("Verbatim Event Date"),
    habitat("Habitat"),
    fieldNumber("Field Number"),
    fieldNotes("Field Notes"),
    eventRemarks("Event Remarks"),
    locationID("Location ID"),
    higherGeographyID("Higher Geography ID"),
    higherGeography("Higher Geography"),
    continent("Continent"),
    waterBody("Water Body"),
    islandGroup("Island Group"),
    island("Island"),
    country("Country"),
    countryCode("Country Code"),
    stateProvince("State Province"),
    county("County"),
    municipality("Municipality"),
    locality("Locality"),
    verbatimLocality("Verbatim Locality"),
    verbatimLocalityID("Verbatim Locality ID"),
    verbatimElevation("Verbatim Elevation"),
    minimumElevationInMeters("Minimum Elevation In Meters"),
    maximumElevationInMeters("Maximum Elevation In Meters"),
    verbatimDepth("Verbatim Depth"),
    minimumDepthInMeters("Minimum Depth In Meters"),
    maximumDepthInMeters("Maximum Depth In Meters"),
    minimumDistanceAboveSurfaceInMeters("Minimum Distance Above Surface In Meters"),
    maximumDistanceAboveSurfaceInMeters("Maximum Distance Above Surface In Meters"),
    locationAccordingTo("Location According To"),
    locationRemarks("Location Remarks"),
    verbatimCoordinates("Verbatim Coordinates"),
    verbatimLatitude("Verbatim Latitude"),
    verbatimLongitude("Verbatim Longitude"),
    verbatimCoordinateSystem("Verbatim Coordinate System"),
    verbatimSRS("Verbatim SRS"),
    decimalLatitude("Decimal Latitude"),
    decimalLongitude("Decimal Longitude"),
    geodeticDatum("Geodetic Datum"),
    coordinateUncertaintyInMeters("Coordinate Uncertainty In Meters"),
    coordinatePrecision("Coordinate Precision"),
    pointRadiusSpatialFit("Point Radius Spatial Fit"),
    footprintWKT("Footprint WKT"),
    footprintSRS("Footprint SRS"),
    footprintSpatialFit("Footprint Spatial Fit"),
    georeferencedBy("Georeferenced By"),
    georeferenceProtocol("Georeference Protocol"),
    georeferenceSources("Georeference Sources"),
    georeferenceVerificationStatus("Georeference Verification Status"),
    georeferenceRemarks("Georeference Remarks"),
    geologicalContextID("Geological Context ID"),
    earliestEonOrLowestEonothem("Earliest EonOr Lowest Eonothem"),
    latestEonOrHighestEonothem("Latest EonOr Highest Eonothem"),
    earliestEraOrLowestErathem("Earliest EraOr Lowest Erathem"),
    latestEraOrHighestErathem("Latest EraOr Highest Erathem"),
    earliestPeriodOrLowestSystem("Earliest Period Or Lowest System"),
    latestPeriodOrHighestSystem("Latest Period Or Highest System"),
    earliestEpochOrLowestSeries("Earliest Epoch Or Lowest Series"),
    latestEpochOrHighestSeries("Latest Epoch Or Highest Series"),
    earliestAgeOrLowestStage("Earliest Age Or Lowest Stage"),
    latestAgeOrHighestStage("Latest Age Or Highest Stage"),
    lowestBiostratigraphicZone("Lowest Biostratigraphic Zone"),
    highestBiostratigraphicZone("Highest Biostratigraphic Zone"),
    lithostratigraphicTerms("Lithostratigraphic Terms"),
    group("Group"),
    formation("Formation"),
    member("Member"),
    bed("Bed"),
    identificationID("Identification ID"),
    identifiedBy("Identified By"),
    dateIdentified("Date Identified"),
    identificationReferences("Identification References"),
    identificationRemarks("Identification Remarks"),
    identificationQualifier("Identification Qualifier"),
    typeStatus("Type Status"),
    taxonID("Taxon ID"),
    scientificNameID("Scientific Name ID"),
    acceptedNameUsageID("Accepted Name Usage ID"),
    parentNameUsageID("Parent Name Usage ID"),
    originalNameUsageID("Original Name Usage ID"),
    nameAccordingToID("Name AccordingTo ID"),
    namePublishedInID("Name PublishedIn ID"),
    taxonConceptID("Taxon Concept ID"),
    scientificName("Scientific Name"),
    acceptedNameUsage("Accepted Name Usage"),
    parentNameUsage("Parent Name Usage"),
    originalNameUsage("Original Name Usage"),
    nameAccordingTo("Name According To"),
    namePublishedIn("Name Published In"),
    higherClassification("Higher Classification"),
    kingdom("Kingdom"),
    phylum("Phylum"),
    clazz("Class"),
    order("Order"),
    family("Family"),
    genus("Genus"),
    subgenus("Subgenus"),
    specificEpithet("Specific Epithet"),
    infraspecificEpithet("Infraspecific Epithet"),
    taxonRank("Taxon Rank"),
    verbatimTaxonRank("Verbatim Taxon Rank"),
    scientificNameAuthorship("Scientific Name Authorship"),
    vernacularName("Vernacular Name"),
    nomenclaturalCode("Nomenclatural Code"),
    taxonomicStatus("Taxonomic Status"),
    nomenclaturalStatus("Nomenclatural Status"),
    taxonRemarks("Taxon Remarks"),
    resourceRelationshipID("Resource Relationship ID"),
    resourceID("Resource ID"),
    relatedResourceID("Related Resource ID"),
    relationshipOfResource("Relationship Of Resource"),
    relationshipAccordingTo("Relationship According To"),
    relationshipEstablishedDate("Relationship Established Date"),
    relationshipRemarks("Relationship Remarks"),
    measurementID("Measurement ID"),
    measurementType("Measurement Type"),
    measurementValue("Measurement Value"),
    measurementAccuracy("Measurement Accuracy"),
    measurementUnit("Measurement Unit"),
    measurementDeterminedDate("Measurement Determined Date"),
    measurementDeterminedBy("Measurement Determined By"),
    measurementMethod("Measurement Method"),
    measurementRemarks("Measurement Remarks"),
    // non DwC
    miscellaneous(""),
    transcriberNotes("Transcriber Notes"),
    validatorNotes("Validator Notes"),
    sequenceNumber("Sequence Number")
    
    def label
    DarwinCoreField(label) { this.label = label }
}

