<%@ page defaultCodec="none" %>
This message was automatically generated by <g:message code="default.application.name"/>. Please do not reply to this message directly.

The task upload process has encountered errors whilst processing the upload queue. Please investigate the errors and reprocess the queue.

Tasks that failed to load:
<g:each in="${errors}" var="error">
 - ${error.projectName} (${error.projectId}): ${error.externalIdentifier}
</g:each>