---

grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.volunteer
    config:
        locations:
            - file:/AM/data/volunteer-portal/config/volunteer-portal-config.properties
            - file:/AM/data/volunteer-portal/config/volunteer-portal-config.yml
            - file:/AM/data/volunteer-portal/config/volunteer-portal-config.groovy
    scaffolding:
        templates:
            domainSuffix: Instance # This causes all respond methods to add the default object as <type>Instance<container>, eg bookInstance or bookInstanceList but does not affect scaffolding in Grails 3... TODO remove Instance from all GSPs and remove this property
    servlet:
        version: 3.0
    spring:
        transactionManagement:
            proxies: false
    mime:
        file:
            extensions: true # enables the parsing of file extensions from URLs into the request format ???
        use:
            accept:
                header: true
        disable:
            accept:
                header:
                    userAgents: false
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
        urlmapping:
            cache:
                maxsize: 1000
        converters:
            encoding: UTF-8
        views:
            default:
                codec: html
            gsp:
                encoding: UTF-8
                htmlcodec: xml
                codecs:
                    expression: html
                    scriptlets: html
                    taglib: none
                    staticparts: none
                sitemesh:
                    preprocess: true
        databinding:
            convertEmptyStringsToNull: false
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 5368709120
            maxRequestSize: 5368709120
    plugins:
        twitterbootstrap:
            fixtaglib: true
    mail:
        default:
            from: 'DigiVol <noreply@volunteer.ala.org.au>'

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
    build:
        ci : '@info.build.ci@'
        date: '@info.build.date@'
        jdk: '@info.build.jdk@'
        number: '@info.build.number@'
    git:
        branch: '@info.git.branch@'
        commit: '@info.git.commit@'
        slug: '@info.git.slug@'
        tag: '@info.git.tag@'
        timestamp: '@info.git.timestamp@'

spring:
    main:
        banner-mode: "console"
    groovy:
        template:
            check-template-location: false
    jmx:
        unique-names: true
    servlet:
        multipart:
            max-file-size: 5000MB
            max-request-size: 5000MB
    devtools:
        restart:
            enabled: true
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**
    flyway:
        enabled: true
        baselineOnMigrate: true
        baselineVersion: 1
        outOfOrder: false
        default-schema: 'public'
        table: 'schema_version'

server:
    tomcat:
        remoteip:
            protocol-header: 'X-Forwarded-Proto'
            port-header: 'X-Forwarded-Port'
            remote-ip-header: 'X-Forwarded-For'
    servlet:
        session:
            timeout: 7200

management:
    endpoints:
        enabled-by-default: false
    server:
        base-path: /status

ala:
    baseURL: "https://www.ala.org.au"
    skin: "digivol-main"
    image:
        service:
            url: https://images.ala.org.au

bie:
    baseURL: "https://bie.ala.org.au"
    searchPath: "/search"

biocache:
    baseURL: "https://biocache.ala.org.au/"

spatial:
    baseURL: "https://spatial.ala.org.au/"

security:
    cas:
        adminRole: "ROLE_VP_ADMIN"
        validatorRole: "ROLE_VP_VALIDATOR"
        uriFilterPattern:
            - "/validate/save*"
            - "/validate/*"
            - "/user/*"
            - "/project/*"
            - "/task/*"
            - "/newsItem/*"
            - "/picklist/*"
            - "/admin"
            - "/admin/*"
            - "/frontPage/*"
            - "/ajax/userReport"
            - "/ws/userReport"
            - "/transcribe/*"
            - "/taskComment/*"
            - "/locality/*"
            - "/collectionEvent/*"
            - "/ajax/keepSessionAlive*"
            - "/ws/keepSessionAlive*"
            - "/forum/*"
            - "/template/*"
            - "/monitoring"
            - "/metrics"
            - "/metrics/*"
            - "/ws/acceptAchievements"
            - "/ajax/acceptAchievements"
            - "/project/createNewProject*"
            - "/message/*"
        authenticateOnlyIfLoggedInPattern:
            - "/"
            - "/;jsessionid=*"
            - "/project/index/*"
            - "/task/summary/*"
            - "/tutorials/*"
            - "/institution/*"
            - "/admin/institutions/*"
            - "/admin/label/*"
            - "/buildInfo"
            - "/events/*"
            - "/es"
            - "/eventSource*"
            - "/wildlife-spotter"
            - "/message/*"
        uriExclusionFilterPattern: '/assets/.*,/static/.*,/fonts/.*,/images/.*,/css/.*,/js/.*,/less/.*,/image/.*'

bvp:
    user:
        activity:
            monitor:
                enabled: true # can turn off activity monitoring
                timeout: 3600 # seconds

    users:
        migrateIds: false
    labels:
        ensureDefault: true
    tmpdir: C:/AM/data/volunteer-portal/config/


images:
    home: C:/AM/data/volunteer-portal
    urlPrefix: /AM/data/volunteer/

elasticsearch:
    location: "/AM/data/volunteer/elasticsearch"

volunteer:
    defaultProjectId: 6306

viewedTask:
    timeout: 7200000 # milliseconds

leaderBoard:
    count: 5

digivol:
    trackJsErrors: false
    trackers:
        - 'UA-4355440-1'
        - 'UA-7855618-24'
        - 'UA-64438237-2'

exportCSVThreadPoolSize: 10

#environments:
#    development:
#        grails:
#            serverURL: http://devt.ala.org.au:8080/digivol
#            mail:
#                disabled: true
#                host: localhost
#                port: 1025
#                #overrideAddress: your.email@here.com
#        server:
#            url: http://devt.ala.org.au
#            contextPath: /digivol
#        security:
#            cas:
#                appServerName: http://devt.ala.org.au:8080
#    test:
#        grails:
#            serverURL: http://volunteer-dev.ala.org.au
#        server:
#            url: http://volunteer-dev.ala.org.au
#        security:
#            cas:
#                appServerName: http://volunteer-dev.ala.org.au
#        images:
#            home: /data/volunteer-portal
#            urlPrefix: data/volunteer-portal/
#        ala:
#            image:
#                service:
#                    url: http://images.ala.org.au
#    production:
#        grails:
#            serverURL: http://volunteer.ala.org.au
#            mail:
#                host: localhost
#                port: 25
#        server:
#            url: http://volunteer.ala.org.au
#        security:
#            cas:
#                appServerName: http://volunteer.ala.org.au

#Fix grails taglib <g:paginate/> to work with bootstrap css.

digest:
    enabled: false
    threshold: 5

quartz:
    autoStartup: true
    jdbcStore: false
    waitForJobsToCompleteOnShutdown: true
    exposeSchedulerInRepository: false
    props:
        scheduler:
            skipUpdateCheck: true

hibernate:
    dialect: net.kaleidos.hibernate.PostgresqlExtensionsDialect
    cache:
        queries: false
        use_query_cache: true
        use_second_level_cache: true
        provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    #SQL="trace,stdout"
    #type="trace,stdout"
    #These next two are needed for grails 3.3.x
    jdbc:
        lob:
            non_contextual_creation: true
    temp:
        use_jdbc_metadata_defaults: false

dataSource:
    dbCreate: validate
    pooled: true
    poolName: 'grails-hikari'
    jmxExport: true
    driverClassName: org.postgresql.Driver
    loggingSql: false
    #username: volunteers
    #password: volunteers

environments:
    development:
        dataSource:
            dbCreate: validate
            url: jdbc:postgresql://localhost:5432/volunteerdb
            #url: jdbc:postgresql://localhost:5432/voltest1
            #username: "postgres"
            #password: "password"
            logSql: false
            properties:
                jdbcInterceptors: ConnectionState;StatementCache(max=200);SlowQueryReport(logFailed=true)
    test:
        elasticsearch:
            location: "./target/elasticsearch/"
        flyway:
            baselineOnMigrate: false
        dataSource:
            dbCreate: validate
            url: jdbc:postgresql://localhost:5432/volunteerstest
            username: "postgres"
            password: "admin"
        quartz:
            autoStartup: false
        grails:
            config:
                locations: []
    production:
        dataSource:
            dbCreate: validate
            properties:
                jmxEnabled: true
                initialSize: 10
                maxActive: 10
                minIdle: 10
                maxIdle: 10
                maxWait: 5000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 5000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState;StatementCache(max=200);SlowQueryReport(logFailed=true)
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
                abandonWhenPercentageFull: 100
                removeAbandonedTimeout: 120
                removeAbandoned: true
                logAbandoned: false
                rollbackOnReturn: true
