---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.volunteer
    config:
        locations:
            - file:/data/volunteer-portal/config/volunteer-portal-config.properties
            - file:/data/volunteer-portal/config/volunteer-portal-config.yml
            - file:/data/volunteer-portal/config/volunteer-portal-config.groovy
            - file:/data/digivol/config/digivol-config.properties
            - file:/data/digivol/config/digivol-config.yml
            - file:/data/digivol/config/digivol-config.groovy
            - file:/etc/digivol/application.properties
            - file:/etc/digivol/application.yml
            - file:/etc/digivol/application.groovy
    scaffolding:
        templates:
            domainSuffix: Instance # This causes all respond methods to add the default object as <type>Instance<container>, eg bookInstance or bookInstanceList but does not affect scaffolding in Grails 3... TODO remove Instance from all GSPs and remove this property
    servlet:
        version: 3.0
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
    build:
        ci : '@info.build.ci@'
        date: '@info.build.date@'
        jdk: '@info.build.jdk@'
        number: '@info.build.number@'
    git:
        branch: '@info.git.branch@'
        commit: '@info.git.commit@'
        slug: '@info.git.slug@'
        tag: '@info.git.tag@'
        timestamp: '@info.git.timestamp@'
spring:
    main:
        banner-mode: "console"
    groovy:
        template:
          check-template-location: false
    http:
        multipart:
          max-file-size: 5000MB
          max-request-size: 5000MB
server:
    session:
        timeout: 7200 # seconds, 2 hours
    tomcat:
        port-header: 'X-Forwarded-Port'
        protocol-header: 'X-Forwarded-Proto'
        remote-ip-header: 'X-Forwarded-For'
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true

---
grails:
    mime:
        file:
            extensions: true # enables the parsing of file extensions from URLs into the request format ???
        use:
            accept:
                header: true
        disable:
            accept:
                header:
                    userAgents: false
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
          maxFileSize: 5368709120
          maxRequestSize: 5368709120
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
            sitemesh:
                preprocess: true
    databinding:
        convertEmptyStringsToNull: false

---
ala:
    baseURL: "http://www.ala.org.au"
    skin: "digivol-main"
    image:
        service:
            url: http://images.ala.org.au

bie:
    baseURL: "http://bie.ala.org.au"
    searchPath: "/search"

biocache:
    baseURL: "http://biocache.ala.org.au/"

spatial:
    baseURL: "http://spatial.ala.org.au/"

security:
    cas:
        adminRole: "ROLE_VP_ADMIN"
        validatorRole: "ROLE_VP_VALIDATOR"
        uriFilterPattern: '/validate/save.*,/validate/.*,/user/.*,/project/((?!index).)*,/task/((?!summary).)*,/newsItem/.*,/picklist/.*,/admin,/admin/.*,/frontPage/.*,/ajax/userReport,/ws/userReport,/transcribe/.*,/taskComment/((?!getCommentsAjax).)*,/locality/.*,/collectionEvent/.*,/ajax/keepSessionAlive.*,/ws/keepSessionAlive.*,/forum/.*,/template/.*,/monitoring,/metrics,/metrics/.*,/ws/acceptAchievements,/ajax/acceptAchievements,/project/createNewProject.*'
        authenticateOnlyIfLoggedInPattern: '/,/;jsessionid=.*,/project/index/.*,/task/summary/.*,/tutorials/.*,/institution/.*,/buildInfo,/events/.*,/es,/eventSource.*,/wildlife-spotter'
        uriExclusionFilterPattern: '/assets/.*,/static/.*,/fonts/.*,/images/.*,/css/.*,/js/.*,/less/.*,/image/.*'

bvp:
    user:
        activity:
            monitor:
                enabled: true # can turn off activity monitoring
                timeout: 3600 # seconds

    users:
        migrateIds: false
    labels:
        ensureDefault: true
    tmpdir: /data/volunteer-portal/config/


images:
    home: /data/volunteer-portal
    urlPrefix: /data/volunteer/

elasticsearch:
    location: "/data/volunteer/elasticsearch"

volunteer:
    defaultProjectId: 6306
viewedTask:
    timeout: 7200000 # milliseconds

leaderBoard:
    count: 5

digivol:
    trackJsErrors: false
    trackers:
        - 'UA-4355440-1'
        - 'UA-7855618-24'
        - 'UA-64438237-2'

#environments:
#    development:
#        grails:
#            serverURL: http://devt.ala.org.au:8080/digivol
#            mail:
#                disabled: true
#                host: localhost
#                port: 1025
#                #overrideAddress: your.email@here.com
#        server:
#            url: http://devt.ala.org.au
#            contextPath: /digivol
#        security:
#            cas:
#                appServerName: http://devt.ala.org.au:8080
#    test:
#        grails:
#            serverURL: http://volunteer-dev.ala.org.au
#        server:
#            url: http://volunteer-dev.ala.org.au
#        security:
#            cas:
#                appServerName: http://volunteer-dev.ala.org.au
#        images:
#            home: /data/volunteer-portal
#            urlPrefix: data/volunteer-portal/
#        ala:
#            image:
#                service:
#                    url: http://images.ala.org.au
#    production:
#        grails:
#            serverURL: http://volunteer.ala.org.au
#            mail:
#                host: localhost
#                port: 25
#        server:
#            url: http://volunteer.ala.org.au
#        security:
#            cas:
#                appServerName: http://volunteer.ala.org.au

#Fix grails taglib <g:paginate/> to work with bootstrap css.
grails:
    plugins:
        twitterbootstrap:
            fixtaglib: true
    mail:
        default:
            from: noreply@volunteer.ala.org.au
digest:
    enabled: false
    threshold: 5
#    address:
---
quartz:
    autoStartup: true
    jdbcStore: false
    waitForJobsToCompleteOnShutdown: true
    exposeSchedulerInRepository: false
    props:
        scheduler:
            skipUpdateCheck: true

environments:
    test:
        quartz:
            autoStartup: false
---
flyway:
    enabled: true
    baselineOnMigrate: true
    baselineVersion: 1
    outOfOrder: true
---
hibernate:
    dialect: net.kaleidos.hibernate.PostgresqlExtensionsDialect
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    #SQL="trace,stdout"
    #type="trace,stdout"

dataSource:
    dbCreate: validate
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
#    username: root
#    password: password
    loggingSql: false

environments:
    development:
        dataSource:
            dbCreate: validate
            url: jdbc:postgresql://localhost/volunteers
            username: "postgres"
            password: "password"
            logSql: false
            properties:
                jdbcInterceptors: ConnectionState;StatementCache(max=200);SlowQueryReport(logFailed=true)
    test:
        elasticsearch:
            location: "./target/elasticsearch/"
        flyway:
            baselineOnMigrate: false
        dataSource:
            dbCreate: validate
            url: jdbc:postgresql://localhost/volunteerstest
            username: "postgres"
            password: "password"
    production:
        dataSource:
            dbCreate: validate
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState;StatementCache(max=200);SlowQueryReport(logFailed=true)
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
                abandonWhenPercentageFull: 100
                removeAbandonedTimeout: 120
                removeAbandoned: true
                logAbandoned: false
